// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/v1/eva_task/task.proto

package eva_task

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseInfo struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Id              string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EvaluationScore int32                     `protobuf:"varint,3,opt,name=evaluationScore,proto3" json:"evaluationScore,omitempty"`
	EvaluationNum   int32                     `protobuf:"varint,4,opt,name=evaluationNum,proto3" json:"evaluationNum,omitempty"`
	TotalNum        int32                     `protobuf:"varint,5,opt,name=totalNum,proto3" json:"totalNum,omitempty"`
	Teacher         []*CourseInfo_TeacherInfo `protobuf:"bytes,6,rep,name=teacher,proto3" json:"teacher,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CourseInfo) Reset() {
	*x = CourseInfo{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseInfo) ProtoMessage() {}

func (x *CourseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseInfo.ProtoReflect.Descriptor instead.
func (*CourseInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{0}
}

func (x *CourseInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CourseInfo) GetEvaluationScore() int32 {
	if x != nil {
		return x.EvaluationScore
	}
	return 0
}

func (x *CourseInfo) GetEvaluationNum() int32 {
	if x != nil {
		return x.EvaluationNum
	}
	return 0
}

func (x *CourseInfo) GetTotalNum() int32 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

func (x *CourseInfo) GetTeacher() []*CourseInfo_TeacherInfo {
	if x != nil {
		return x.Teacher
	}
	return nil
}

type TaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Course        []*CourseInfo          `protobuf:"bytes,4,rep,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TaskInfo) GetCourse() []*CourseInfo {
	if x != nil {
		return x.Course
	}
	return nil
}

type CreateTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CourseIds     []int32                `protobuf:"varint,2,rep,packed,name=courseIds,proto3" json:"courseIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskReq) Reset() {
	*x = CreateTaskReq{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskReq) ProtoMessage() {}

func (x *CreateTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskReq.ProtoReflect.Descriptor instead.
func (*CreateTaskReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskReq) GetCourseIds() []int32 {
	if x != nil {
		return x.CourseIds
	}
	return nil
}

type CreateTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CreateTaskRespD       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResp) Reset() {
	*x = CreateTaskResp{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResp) ProtoMessage() {}

func (x *CreateTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResp.ProtoReflect.Descriptor instead.
func (*CreateTaskResp) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTaskResp) GetData() *CreateTaskRespD {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReq) Reset() {
	*x = GetTaskReq{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReq) ProtoMessage() {}

func (x *GetTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReq.ProtoReflect.Descriptor instead.
func (*GetTaskReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskListReq) Reset() {
	*x = GetTaskListReq{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskListReq) ProtoMessage() {}

func (x *GetTaskListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskListReq.ProtoReflect.Descriptor instead.
func (*GetTaskListReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTaskListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTaskListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetTaskListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetTaskListRespD      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskListResp) Reset() {
	*x = GetTaskListResp{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskListResp) ProtoMessage() {}

func (x *GetTaskListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskListResp.ProtoReflect.Descriptor instead.
func (*GetTaskListResp) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTaskListResp) GetData() *GetTaskListRespD {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChangeTaskStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTaskStatusReq) Reset() {
	*x = ChangeTaskStatusReq{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTaskStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTaskStatusReq) ProtoMessage() {}

func (x *ChangeTaskStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTaskStatusReq.ProtoReflect.Descriptor instead.
func (*ChangeTaskStatusReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeTaskStatusReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangeTaskStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ChangeTaskStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTaskStatusResp) Reset() {
	*x = ChangeTaskStatusResp{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTaskStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTaskStatusResp) ProtoMessage() {}

func (x *ChangeTaskStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTaskStatusResp.ProtoReflect.Descriptor instead.
func (*ChangeTaskStatusResp) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeTaskStatusResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StuTaskDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint32                 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	StuNo         string                 `protobuf:"bytes,2,opt,name=stuNo,proto3" json:"stuNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StuTaskDetailReq) Reset() {
	*x = StuTaskDetailReq{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StuTaskDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StuTaskDetailReq) ProtoMessage() {}

func (x *StuTaskDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StuTaskDetailReq.ProtoReflect.Descriptor instead.
func (*StuTaskDetailReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{9}
}

func (x *StuTaskDetailReq) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *StuTaskDetailReq) GetStuNo() string {
	if x != nil {
		return x.StuNo
	}
	return ""
}

type StuTaskDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Course        []*CourseInfo          `protobuf:"bytes,2,rep,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StuTaskDetailRes) Reset() {
	*x = StuTaskDetailRes{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StuTaskDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StuTaskDetailRes) ProtoMessage() {}

func (x *StuTaskDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StuTaskDetailRes.ProtoReflect.Descriptor instead.
func (*StuTaskDetailRes) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{10}
}

func (x *StuTaskDetailRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StuTaskDetailRes) GetCourse() []*CourseInfo {
	if x != nil {
		return x.Course
	}
	return nil
}

type SubmitEvaluationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint32                 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	CourseId      uint32                 `protobuf:"varint,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	TeacherId     uint32                 `protobuf:"varint,3,opt,name=teacherId,proto3" json:"teacherId,omitempty"`
	StuNo         string                 `protobuf:"bytes,4,opt,name=stuNo,proto3" json:"stuNo,omitempty"`
	DetailScore   string                 `protobuf:"bytes,5,opt,name=detailScore,proto3" json:"detailScore,omitempty"`
	Score         int32                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	Comment       string                 `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitEvaluationReq) Reset() {
	*x = SubmitEvaluationReq{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEvaluationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEvaluationReq) ProtoMessage() {}

func (x *SubmitEvaluationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEvaluationReq.ProtoReflect.Descriptor instead.
func (*SubmitEvaluationReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitEvaluationReq) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SubmitEvaluationReq) GetCourseId() uint32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *SubmitEvaluationReq) GetTeacherId() uint32 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *SubmitEvaluationReq) GetStuNo() string {
	if x != nil {
		return x.StuNo
	}
	return ""
}

func (x *SubmitEvaluationReq) GetDetailScore() string {
	if x != nil {
		return x.DetailScore
	}
	return ""
}

func (x *SubmitEvaluationReq) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitEvaluationReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SubmitEvaluationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitEvaluationResp) Reset() {
	*x = SubmitEvaluationResp{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEvaluationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEvaluationResp) ProtoMessage() {}

func (x *SubmitEvaluationResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEvaluationResp.ProtoReflect.Descriptor instead.
func (*SubmitEvaluationResp) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitEvaluationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExportTaskResultsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint32                 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTaskResultsReq) Reset() {
	*x = ExportTaskResultsReq{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTaskResultsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTaskResultsReq) ProtoMessage() {}

func (x *ExportTaskResultsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTaskResultsReq.ProtoReflect.Descriptor instead.
func (*ExportTaskResultsReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{13}
}

func (x *ExportTaskResultsReq) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ExportTaskResultsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ZipPath       string                 `protobuf:"bytes,4,opt,name=zipPath,proto3" json:"zipPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTaskResultsResp) Reset() {
	*x = ExportTaskResultsResp{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTaskResultsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTaskResultsResp) ProtoMessage() {}

func (x *ExportTaskResultsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTaskResultsResp.ProtoReflect.Descriptor instead.
func (*ExportTaskResultsResp) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{14}
}

func (x *ExportTaskResultsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExportTaskResultsResp) GetZipPath() string {
	if x != nil {
		return x.ZipPath
	}
	return ""
}

type CourseInfo_TeacherInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HasEvaluation bool                   `protobuf:"varint,3,opt,name=hasEvaluation,proto3" json:"hasEvaluation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseInfo_TeacherInfo) Reset() {
	*x = CourseInfo_TeacherInfo{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseInfo_TeacherInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseInfo_TeacherInfo) ProtoMessage() {}

func (x *CourseInfo_TeacherInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseInfo_TeacherInfo.ProtoReflect.Descriptor instead.
func (*CourseInfo_TeacherInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CourseInfo_TeacherInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseInfo_TeacherInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CourseInfo_TeacherInfo) GetHasEvaluation() bool {
	if x != nil {
		return x.HasEvaluation
	}
	return false
}

type CreateTaskRespD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRespD) Reset() {
	*x = CreateTaskRespD{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRespD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRespD) ProtoMessage() {}

func (x *CreateTaskRespD) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRespD.ProtoReflect.Descriptor instead.
func (*CreateTaskRespD) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CreateTaskRespD) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskListRespD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskListRespD) Reset() {
	*x = GetTaskListRespD{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskListRespD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskListRespD) ProtoMessage() {}

func (x *GetTaskListRespD) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskListRespD.ProtoReflect.Descriptor instead.
func (*GetTaskListRespD) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetTaskListRespD) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *GetTaskListRespD) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_v1_eva_task_task_proto protoreflect.FileDescriptor

const file_api_v1_eva_task_task_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/v1/eva_task/task.proto\x12\x0fapi.v1.eva_task\x1a\x1cgoogle/api/annotations.proto\"\xb8\x02\n" +
	"\n" +
	"CourseInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x0fevaluationScore\x18\x03 \x01(\x05R\x0fevaluationScore\x12$\n" +
	"\revaluationNum\x18\x04 \x01(\x05R\revaluationNum\x12\x1a\n" +
	"\btotalNum\x18\x05 \x01(\x05R\btotalNum\x12A\n" +
	"\ateacher\x18\x06 \x03(\v2'.api.v1.eva_task.CourseInfo.TeacherInfoR\ateacher\x1aW\n" +
	"\vTeacherInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\rhasEvaluation\x18\x03 \x01(\bR\rhasEvaluation\"{\n" +
	"\bTaskInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x123\n" +
	"\x06course\x18\x04 \x03(\v2\x1b.api.v1.eva_task.CourseInfoR\x06course\"A\n" +
	"\rCreateTaskReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tcourseIds\x18\x02 \x03(\x05R\tcourseIds\"v\n" +
	"\x0eCreateTaskResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x02 \x01(\v2!.api.v1.eva_task.CreateTaskResp.dR\x04data\x1a\x13\n" +
	"\x01d\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\n" +
	"GetTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x0eGetTaskListReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"\xaf\x01\n" +
	"\x0fGetTaskListResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x02 \x01(\v2\".api.v1.eva_task.GetTaskListResp.dR\x04data\x1aJ\n" +
	"\x01d\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.api.v1.eva_task.TaskInfoR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"=\n" +
	"\x13ChangeTaskStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"0\n" +
	"\x14ChangeTaskStatusResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"@\n" +
	"\x10StuTaskDetailReq\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\rR\x06taskId\x12\x14\n" +
	"\x05stuNo\x18\x02 \x01(\tR\x05stuNo\"a\n" +
	"\x10StuTaskDetailRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x123\n" +
	"\x06course\x18\x02 \x03(\v2\x1b.api.v1.eva_task.CourseInfoR\x06course\"\xcf\x01\n" +
	"\x13SubmitEvaluationReq\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\rR\x06taskId\x12\x1a\n" +
	"\bcourseId\x18\x02 \x01(\rR\bcourseId\x12\x1c\n" +
	"\tteacherId\x18\x03 \x01(\rR\tteacherId\x12\x14\n" +
	"\x05stuNo\x18\x04 \x01(\tR\x05stuNo\x12 \n" +
	"\vdetailScore\x18\x05 \x01(\tR\vdetailScore\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x05R\x05score\x12\x18\n" +
	"\acomment\x18\a \x01(\tR\acomment\"0\n" +
	"\x14SubmitEvaluationResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\x14ExportTaskResultsReq\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\rR\x06taskId\"K\n" +
	"\x15ExportTaskResultsResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\azipPath\x18\x04 \x01(\tR\azipPath2\xd3\x06\n" +
	"\x04Task\x12m\n" +
	"\n" +
	"CreateTask\x12\x1e.api.v1.eva_task.CreateTaskReq\x1a\x1f.api.v1.eva_task.CreateTaskResp\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/task/create\x12d\n" +
	"\x04List\x12\x1f.api.v1.eva_task.GetTaskListReq\x1a .api.v1.eva_task.GetTaskListResp\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/task/list\x12\x83\x01\n" +
	"\x11StudentTaskDetail\x12!.api.v1.eva_task.StuTaskDetailReq\x1a!.api.v1.eva_task.StuTaskDetailRes\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/task/student_task_detail\x12]\n" +
	"\x06Detail\x12\x1b.api.v1.eva_task.GetTaskReq\x1a\x19.api.v1.eva_task.TaskInfo\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/task/detail\x12\x82\x01\n" +
	"\fChangeStatus\x12$.api.v1.eva_task.ChangeTaskStatusReq\x1a%.api.v1.eva_task.ChangeTaskStatusResp\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/task/change_status\x12\x8a\x01\n" +
	"\x10SubmitEvaluation\x12$.api.v1.eva_task.SubmitEvaluationReq\x1a%.api.v1.eva_task.SubmitEvaluationResp\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/task/submit_evaluation\x12\x7f\n" +
	"\x11ExportTaskResults\x12%.api.v1.eva_task.ExportTaskResultsReq\x1a&.api.v1.eva_task.ExportTaskResultsResp\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/task/exportBC\n" +
	"\x0fapi.v1.eva_taskP\x01Z.edu-evaluation-backed/api/v1/eva_task;eva_taskb\x06proto3"

var (
	file_api_v1_eva_task_task_proto_rawDescOnce sync.Once
	file_api_v1_eva_task_task_proto_rawDescData []byte
)

func file_api_v1_eva_task_task_proto_rawDescGZIP() []byte {
	file_api_v1_eva_task_task_proto_rawDescOnce.Do(func() {
		file_api_v1_eva_task_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_eva_task_task_proto_rawDesc), len(file_api_v1_eva_task_task_proto_rawDesc)))
	})
	return file_api_v1_eva_task_task_proto_rawDescData
}

var file_api_v1_eva_task_task_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_v1_eva_task_task_proto_goTypes = []any{
	(*CourseInfo)(nil),             // 0: api.v1.eva_task.CourseInfo
	(*TaskInfo)(nil),               // 1: api.v1.eva_task.TaskInfo
	(*CreateTaskReq)(nil),          // 2: api.v1.eva_task.CreateTaskReq
	(*CreateTaskResp)(nil),         // 3: api.v1.eva_task.CreateTaskResp
	(*GetTaskReq)(nil),             // 4: api.v1.eva_task.GetTaskReq
	(*GetTaskListReq)(nil),         // 5: api.v1.eva_task.GetTaskListReq
	(*GetTaskListResp)(nil),        // 6: api.v1.eva_task.GetTaskListResp
	(*ChangeTaskStatusReq)(nil),    // 7: api.v1.eva_task.ChangeTaskStatusReq
	(*ChangeTaskStatusResp)(nil),   // 8: api.v1.eva_task.ChangeTaskStatusResp
	(*StuTaskDetailReq)(nil),       // 9: api.v1.eva_task.StuTaskDetailReq
	(*StuTaskDetailRes)(nil),       // 10: api.v1.eva_task.StuTaskDetailRes
	(*SubmitEvaluationReq)(nil),    // 11: api.v1.eva_task.SubmitEvaluationReq
	(*SubmitEvaluationResp)(nil),   // 12: api.v1.eva_task.SubmitEvaluationResp
	(*ExportTaskResultsReq)(nil),   // 13: api.v1.eva_task.ExportTaskResultsReq
	(*ExportTaskResultsResp)(nil),  // 14: api.v1.eva_task.ExportTaskResultsResp
	(*CourseInfo_TeacherInfo)(nil), // 15: api.v1.eva_task.CourseInfo.TeacherInfo
	(*CreateTaskRespD)(nil),        // 16: api.v1.eva_task.CreateTaskResp.d
	(*GetTaskListRespD)(nil),       // 17: api.v1.eva_task.GetTaskListResp.d
}
var file_api_v1_eva_task_task_proto_depIdxs = []int32{
	15, // 0: api.v1.eva_task.CourseInfo.teacher:type_name -> api.v1.eva_task.CourseInfo.TeacherInfo
	0,  // 1: api.v1.eva_task.TaskInfo.course:type_name -> api.v1.eva_task.CourseInfo
	16, // 2: api.v1.eva_task.CreateTaskResp.data:type_name -> api.v1.eva_task.CreateTaskResp.d
	17, // 3: api.v1.eva_task.GetTaskListResp.data:type_name -> api.v1.eva_task.GetTaskListResp.d
	0,  // 4: api.v1.eva_task.StuTaskDetailRes.course:type_name -> api.v1.eva_task.CourseInfo
	1,  // 5: api.v1.eva_task.GetTaskListResp.d.tasks:type_name -> api.v1.eva_task.TaskInfo
	2,  // 6: api.v1.eva_task.Task.CreateTask:input_type -> api.v1.eva_task.CreateTaskReq
	5,  // 7: api.v1.eva_task.Task.List:input_type -> api.v1.eva_task.GetTaskListReq
	9,  // 8: api.v1.eva_task.Task.StudentTaskDetail:input_type -> api.v1.eva_task.StuTaskDetailReq
	4,  // 9: api.v1.eva_task.Task.Detail:input_type -> api.v1.eva_task.GetTaskReq
	7,  // 10: api.v1.eva_task.Task.ChangeStatus:input_type -> api.v1.eva_task.ChangeTaskStatusReq
	11, // 11: api.v1.eva_task.Task.SubmitEvaluation:input_type -> api.v1.eva_task.SubmitEvaluationReq
	13, // 12: api.v1.eva_task.Task.ExportTaskResults:input_type -> api.v1.eva_task.ExportTaskResultsReq
	3,  // 13: api.v1.eva_task.Task.CreateTask:output_type -> api.v1.eva_task.CreateTaskResp
	6,  // 14: api.v1.eva_task.Task.List:output_type -> api.v1.eva_task.GetTaskListResp
	10, // 15: api.v1.eva_task.Task.StudentTaskDetail:output_type -> api.v1.eva_task.StuTaskDetailRes
	1,  // 16: api.v1.eva_task.Task.Detail:output_type -> api.v1.eva_task.TaskInfo
	8,  // 17: api.v1.eva_task.Task.ChangeStatus:output_type -> api.v1.eva_task.ChangeTaskStatusResp
	12, // 18: api.v1.eva_task.Task.SubmitEvaluation:output_type -> api.v1.eva_task.SubmitEvaluationResp
	14, // 19: api.v1.eva_task.Task.ExportTaskResults:output_type -> api.v1.eva_task.ExportTaskResultsResp
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_eva_task_task_proto_init() }
func file_api_v1_eva_task_task_proto_init() {
	if File_api_v1_eva_task_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_eva_task_task_proto_rawDesc), len(file_api_v1_eva_task_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_eva_task_task_proto_goTypes,
		DependencyIndexes: file_api_v1_eva_task_task_proto_depIdxs,
		MessageInfos:      file_api_v1_eva_task_task_proto_msgTypes,
	}.Build()
	File_api_v1_eva_task_task_proto = out.File
	file_api_v1_eva_task_task_proto_goTypes = nil
	file_api_v1_eva_task_task_proto_depIdxs = nil
}
