// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: api/v1/eva_task/task.proto

package eva_task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Task_CreateTask_FullMethodName        = "/api.v1.eva_task.Task/CreateTask"
	Task_List_FullMethodName              = "/api.v1.eva_task.Task/List"
	Task_StudentTaskDetail_FullMethodName = "/api.v1.eva_task.Task/StudentTaskDetail"
	Task_Detail_FullMethodName            = "/api.v1.eva_task.Task/Detail"
	Task_ChangeStatus_FullMethodName      = "/api.v1.eva_task.Task/ChangeStatus"
	Task_SubmitEvaluation_FullMethodName  = "/api.v1.eva_task.Task/SubmitEvaluation"
	Task_ExportTaskResults_FullMethodName = "/api.v1.eva_task.Task/ExportTaskResults"
)

// TaskClient is the client API for Task service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskClient interface {
	CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskResp, error)
	List(ctx context.Context, in *GetTaskListReq, opts ...grpc.CallOption) (*GetTaskListResp, error)
	StudentTaskDetail(ctx context.Context, in *StuTaskDetailReq, opts ...grpc.CallOption) (*StuTaskDetailRes, error)
	Detail(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*TaskInfo, error)
	ChangeStatus(ctx context.Context, in *ChangeTaskStatusReq, opts ...grpc.CallOption) (*ChangeTaskStatusResp, error)
	SubmitEvaluation(ctx context.Context, in *SubmitEvaluationReq, opts ...grpc.CallOption) (*SubmitEvaluationResp, error)
	ExportTaskResults(ctx context.Context, in *ExportTaskResultsReq, opts ...grpc.CallOption) (*ExportTaskResultsResp, error)
}

type taskClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskClient(cc grpc.ClientConnInterface) TaskClient {
	return &taskClient{cc}
}

func (c *taskClient) CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResp)
	err := c.cc.Invoke(ctx, Task_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) List(ctx context.Context, in *GetTaskListReq, opts ...grpc.CallOption) (*GetTaskListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskListResp)
	err := c.cc.Invoke(ctx, Task_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) StudentTaskDetail(ctx context.Context, in *StuTaskDetailReq, opts ...grpc.CallOption) (*StuTaskDetailRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StuTaskDetailRes)
	err := c.cc.Invoke(ctx, Task_StudentTaskDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) Detail(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*TaskInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskInfo)
	err := c.cc.Invoke(ctx, Task_Detail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) ChangeStatus(ctx context.Context, in *ChangeTaskStatusReq, opts ...grpc.CallOption) (*ChangeTaskStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeTaskStatusResp)
	err := c.cc.Invoke(ctx, Task_ChangeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) SubmitEvaluation(ctx context.Context, in *SubmitEvaluationReq, opts ...grpc.CallOption) (*SubmitEvaluationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitEvaluationResp)
	err := c.cc.Invoke(ctx, Task_SubmitEvaluation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) ExportTaskResults(ctx context.Context, in *ExportTaskResultsReq, opts ...grpc.CallOption) (*ExportTaskResultsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportTaskResultsResp)
	err := c.cc.Invoke(ctx, Task_ExportTaskResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServer is the server API for Task service.
// All implementations must embed UnimplementedTaskServer
// for forward compatibility.
type TaskServer interface {
	CreateTask(context.Context, *CreateTaskReq) (*CreateTaskResp, error)
	List(context.Context, *GetTaskListReq) (*GetTaskListResp, error)
	StudentTaskDetail(context.Context, *StuTaskDetailReq) (*StuTaskDetailRes, error)
	Detail(context.Context, *GetTaskReq) (*TaskInfo, error)
	ChangeStatus(context.Context, *ChangeTaskStatusReq) (*ChangeTaskStatusResp, error)
	SubmitEvaluation(context.Context, *SubmitEvaluationReq) (*SubmitEvaluationResp, error)
	ExportTaskResults(context.Context, *ExportTaskResultsReq) (*ExportTaskResultsResp, error)
	mustEmbedUnimplementedTaskServer()
}

// UnimplementedTaskServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServer struct{}

func (UnimplementedTaskServer) CreateTask(context.Context, *CreateTaskReq) (*CreateTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTaskServer) List(context.Context, *GetTaskListReq) (*GetTaskListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTaskServer) StudentTaskDetail(context.Context, *StuTaskDetailReq) (*StuTaskDetailRes, error) {
	return nil, status.Error(codes.Unimplemented, "method StudentTaskDetail not implemented")
}
func (UnimplementedTaskServer) Detail(context.Context, *GetTaskReq) (*TaskInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Detail not implemented")
}
func (UnimplementedTaskServer) ChangeStatus(context.Context, *ChangeTaskStatusReq) (*ChangeTaskStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeStatus not implemented")
}
func (UnimplementedTaskServer) SubmitEvaluation(context.Context, *SubmitEvaluationReq) (*SubmitEvaluationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitEvaluation not implemented")
}
func (UnimplementedTaskServer) ExportTaskResults(context.Context, *ExportTaskResultsReq) (*ExportTaskResultsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportTaskResults not implemented")
}
func (UnimplementedTaskServer) mustEmbedUnimplementedTaskServer() {}
func (UnimplementedTaskServer) testEmbeddedByValue()              {}

// UnsafeTaskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServer will
// result in compilation errors.
type UnsafeTaskServer interface {
	mustEmbedUnimplementedTaskServer()
}

func RegisterTaskServer(s grpc.ServiceRegistrar, srv TaskServer) {
	// If the following call panics, it indicates UnimplementedTaskServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Task_ServiceDesc, srv)
}

func _Task_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).CreateTask(ctx, req.(*CreateTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).List(ctx, req.(*GetTaskListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_StudentTaskDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StuTaskDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).StudentTaskDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_StudentTaskDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).StudentTaskDetail(ctx, req.(*StuTaskDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_Detail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).Detail(ctx, req.(*GetTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_ChangeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeTaskStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).ChangeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_ChangeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).ChangeStatus(ctx, req.(*ChangeTaskStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_SubmitEvaluation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitEvaluationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).SubmitEvaluation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_SubmitEvaluation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).SubmitEvaluation(ctx, req.(*SubmitEvaluationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_ExportTaskResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportTaskResultsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).ExportTaskResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_ExportTaskResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).ExportTaskResults(ctx, req.(*ExportTaskResultsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Task_ServiceDesc is the grpc.ServiceDesc for Task service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Task_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.eva_task.Task",
	HandlerType: (*TaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _Task_CreateTask_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Task_List_Handler,
		},
		{
			MethodName: "StudentTaskDetail",
			Handler:    _Task_StudentTaskDetail_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _Task_Detail_Handler,
		},
		{
			MethodName: "ChangeStatus",
			Handler:    _Task_ChangeStatus_Handler,
		},
		{
			MethodName: "SubmitEvaluation",
			Handler:    _Task_SubmitEvaluation_Handler,
		},
		{
			MethodName: "ExportTaskResults",
			Handler:    _Task_ExportTaskResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/eva_task/task.proto",
}
