// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/v1/eva_task/task.proto

package eva_task

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Course        []*TaskInfo_CourseInfo `protobuf:"bytes,3,rep,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskInfo) GetCourse() []*TaskInfo_CourseInfo {
	if x != nil {
		return x.Course
	}
	return nil
}

type CreateTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CourseIds     []int32                `protobuf:"varint,2,rep,packed,name=courseIds,proto3" json:"courseIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskReq) Reset() {
	*x = CreateTaskReq{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskReq) ProtoMessage() {}

func (x *CreateTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskReq.ProtoReflect.Descriptor instead.
func (*CreateTaskReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskReq) GetCourseIds() []int32 {
	if x != nil {
		return x.CourseIds
	}
	return nil
}

type CreateTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResp) Reset() {
	*x = CreateTaskResp{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResp) ProtoMessage() {}

func (x *CreateTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResp.ProtoReflect.Descriptor instead.
func (*CreateTaskResp) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTaskResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReq) Reset() {
	*x = GetTaskReq{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReq) ProtoMessage() {}

func (x *GetTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReq.ProtoReflect.Descriptor instead.
func (*GetTaskReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskListReq) Reset() {
	*x = GetTaskListReq{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskListReq) ProtoMessage() {}

func (x *GetTaskListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskListReq.ProtoReflect.Descriptor instead.
func (*GetTaskListReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTaskListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTaskListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetTaskListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskListResp) Reset() {
	*x = GetTaskListResp{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskListResp) ProtoMessage() {}

func (x *GetTaskListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskListResp.ProtoReflect.Descriptor instead.
func (*GetTaskListResp) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskListResp) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskInfo_CourseInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EvaluationScore int32                  `protobuf:"varint,3,opt,name=evaluationScore,proto3" json:"evaluationScore,omitempty"`
	EvaluationNum   int32                  `protobuf:"varint,4,opt,name=evaluationNum,proto3" json:"evaluationNum,omitempty"`
	TotalNum        int32                  `protobuf:"varint,5,opt,name=totalNum,proto3" json:"totalNum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskInfo_CourseInfo) Reset() {
	*x = TaskInfo_CourseInfo{}
	mi := &file_api_v1_eva_task_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo_CourseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo_CourseInfo) ProtoMessage() {}

func (x *TaskInfo_CourseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_task_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo_CourseInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo_CourseInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_task_task_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TaskInfo_CourseInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskInfo_CourseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskInfo_CourseInfo) GetEvaluationScore() int32 {
	if x != nil {
		return x.EvaluationScore
	}
	return 0
}

func (x *TaskInfo_CourseInfo) GetEvaluationNum() int32 {
	if x != nil {
		return x.EvaluationNum
	}
	return 0
}

func (x *TaskInfo_CourseInfo) GetTotalNum() int32 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

var File_api_v1_eva_task_task_proto protoreflect.FileDescriptor

const file_api_v1_eva_task_task_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/v1/eva_task/task.proto\x12\x0fapi.v1.eva_task\x1a\x1cgoogle/api/annotations.proto\"\x8b\x02\n" +
	"\bTaskInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12<\n" +
	"\x06course\x18\x03 \x03(\v2$.api.v1.eva_task.TaskInfo.CourseInfoR\x06course\x1a\x9c\x01\n" +
	"\n" +
	"CourseInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x0fevaluationScore\x18\x03 \x01(\x05R\x0fevaluationScore\x12$\n" +
	"\revaluationNum\x18\x04 \x01(\x05R\revaluationNum\x12\x1a\n" +
	"\btotalNum\x18\x05 \x01(\x05R\btotalNum\"A\n" +
	"\rCreateTaskReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tcourseIds\x18\x02 \x03(\x05R\tcourseIds\":\n" +
	"\x0eCreateTaskResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x1c\n" +
	"\n" +
	"GetTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x0eGetTaskListReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"B\n" +
	"\x0fGetTaskListResp\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.api.v1.eva_task.TaskInfoR\x05tasks2\xb6\x02\n" +
	"\x04Task\x12m\n" +
	"\n" +
	"CreateTask\x12\x1e.api.v1.eva_task.CreateTaskReq\x1a\x1f.api.v1.eva_task.CreateTaskResp\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/task/create\x12`\n" +
	"\x04List\x12\x1b.api.v1.eva_task.GetTaskReq\x1a .api.v1.eva_task.GetTaskListResp\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/task/list\x12]\n" +
	"\x06Detail\x12\x1b.api.v1.eva_task.GetTaskReq\x1a\x19.api.v1.eva_task.TaskInfo\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/task/detailBC\n" +
	"\x0fapi.v1.eva_taskP\x01Z.edu-evaluation-backed/api/v1/eva_task;eva_taskb\x06proto3"

var (
	file_api_v1_eva_task_task_proto_rawDescOnce sync.Once
	file_api_v1_eva_task_task_proto_rawDescData []byte
)

func file_api_v1_eva_task_task_proto_rawDescGZIP() []byte {
	file_api_v1_eva_task_task_proto_rawDescOnce.Do(func() {
		file_api_v1_eva_task_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_eva_task_task_proto_rawDesc), len(file_api_v1_eva_task_task_proto_rawDesc)))
	})
	return file_api_v1_eva_task_task_proto_rawDescData
}

var file_api_v1_eva_task_task_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_eva_task_task_proto_goTypes = []any{
	(*TaskInfo)(nil),            // 0: api.v1.eva_task.TaskInfo
	(*CreateTaskReq)(nil),       // 1: api.v1.eva_task.CreateTaskReq
	(*CreateTaskResp)(nil),      // 2: api.v1.eva_task.CreateTaskResp
	(*GetTaskReq)(nil),          // 3: api.v1.eva_task.GetTaskReq
	(*GetTaskListReq)(nil),      // 4: api.v1.eva_task.GetTaskListReq
	(*GetTaskListResp)(nil),     // 5: api.v1.eva_task.GetTaskListResp
	(*TaskInfo_CourseInfo)(nil), // 6: api.v1.eva_task.TaskInfo.CourseInfo
}
var file_api_v1_eva_task_task_proto_depIdxs = []int32{
	6, // 0: api.v1.eva_task.TaskInfo.course:type_name -> api.v1.eva_task.TaskInfo.CourseInfo
	0, // 1: api.v1.eva_task.GetTaskListResp.tasks:type_name -> api.v1.eva_task.TaskInfo
	1, // 2: api.v1.eva_task.Task.CreateTask:input_type -> api.v1.eva_task.CreateTaskReq
	3, // 3: api.v1.eva_task.Task.List:input_type -> api.v1.eva_task.GetTaskReq
	3, // 4: api.v1.eva_task.Task.Detail:input_type -> api.v1.eva_task.GetTaskReq
	2, // 5: api.v1.eva_task.Task.CreateTask:output_type -> api.v1.eva_task.CreateTaskResp
	5, // 6: api.v1.eva_task.Task.List:output_type -> api.v1.eva_task.GetTaskListResp
	0, // 7: api.v1.eva_task.Task.Detail:output_type -> api.v1.eva_task.TaskInfo
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_eva_task_task_proto_init() }
func file_api_v1_eva_task_task_proto_init() {
	if File_api_v1_eva_task_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_eva_task_task_proto_rawDesc), len(file_api_v1_eva_task_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_eva_task_task_proto_goTypes,
		DependencyIndexes: file_api_v1_eva_task_task_proto_depIdxs,
		MessageInfos:      file_api_v1_eva_task_task_proto_msgTypes,
	}.Build()
	File_api_v1_eva_task_task_proto = out.File
	file_api_v1_eva_task_task_proto_goTypes = nil
	file_api_v1_eva_task_task_proto_depIdxs = nil
}
