// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"edu-evaluation-backed/internal/biz/auth"
	"edu-evaluation-backed/internal/biz/base_info"
	"edu-evaluation-backed/internal/biz/eva_question"
	"edu-evaluation-backed/internal/biz/eva_task"
	"edu-evaluation-backed/internal/conf"
	"edu-evaluation-backed/internal/data"
	"edu-evaluation-backed/internal/data/dal"
	"edu-evaluation-backed/internal/server"
	auth2 "edu-evaluation-backed/internal/service/auth"
	base_info2 "edu-evaluation-backed/internal/service/base_info"
	eva_question2 "edu-evaluation-backed/internal/service/eva_question"
	eva_task2 "edu-evaluation-backed/internal/service/eva_task"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	baseInfoDal := dal.NewBaseInfoDal(dataData)
	authUseCase := auth.NewAuthUseCase(baseInfoDal)
	authService := auth2.NewAuthService(authUseCase)
	studentUseCase := base_info.NewStudentUseCase(baseInfoDal)
	studentService := base_info2.NewStudentService(studentUseCase, baseInfoDal)
	teacherUseCase := base_info.NewTeacherUseCase(baseInfoDal)
	teacherService := base_info2.NewTeacherService(teacherUseCase, baseInfoDal)
	baseDal := dal.NewBaseDal(dataData)
	courseDal := dal.NewCourseDal(dataData)
	courseUseCase := base_info.NewCourseUseCase(courseDal, baseInfoDal)
	courseService := base_info2.NewCourseService(baseDal, courseDal, courseUseCase)
	taskDal := dal.NewTaskDal(dataData)
	evaTaskUseCase := eva_task.NewEvaTaskUseCase(baseInfoDal, taskDal, courseDal)
	evaTaskService := eva_task2.NewEvaTaskService(taskDal, evaTaskUseCase)
	questionDal := dal.NewQuestionDal(dataData)
	questionUseCase := eva_question.NewQuestionUseCase(questionDal)
	questionService := eva_question2.NewQuestionService(questionUseCase)
	httpServer := server.NewHTTPServer(confServer, authService, studentService, teacherService, courseService, evaTaskService, questionService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
