// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/v1/base_info/course/course.proto

package course

import (
	student "edu-evaluation-backed/api/v1/base_info/student"
	teacher "edu-evaluation-backed/api/v1/base_info/teacher"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseName    string                 `protobuf:"bytes,2,opt,name=courseName,proto3" json:"courseName,omitempty"`
	ClassName     string                 `protobuf:"bytes,3,opt,name=className,proto3" json:"className,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	TeacherList   []*teacher.TeacherInfo `protobuf:"bytes,4,rep,name=teacherList,proto3" json:"teacherList,omitempty"`
	StudentList   []*student.StudentInfo `protobuf:"bytes,5,rep,name=studentList,proto3" json:"studentList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseList) Reset() {
	*x = CourseList{}
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseList) ProtoMessage() {}

func (x *CourseList) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseList.ProtoReflect.Descriptor instead.
func (*CourseList) Descriptor() ([]byte, []int) {
	return file_api_v1_base_info_course_course_proto_rawDescGZIP(), []int{0}
}

func (x *CourseList) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourseList) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *CourseList) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *CourseList) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CourseList) GetTeacherList() []*teacher.TeacherInfo {
	if x != nil {
		return x.TeacherList
	}
	return nil
}

func (x *CourseList) GetStudentList() []*student.StudentInfo {
	if x != nil {
		return x.StudentList
	}
	return nil
}

type GetCourseListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseListReq) Reset() {
	*x = GetCourseListReq{}
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseListReq) ProtoMessage() {}

func (x *GetCourseListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseListReq.ProtoReflect.Descriptor instead.
func (*GetCourseListReq) Descriptor() ([]byte, []int) {
	return file_api_v1_base_info_course_course_proto_rawDescGZIP(), []int{1}
}

func (x *GetCourseListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCourseListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCourseListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CourseList          `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseListResp) Reset() {
	*x = GetCourseListResp{}
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseListResp) ProtoMessage() {}

func (x *GetCourseListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseListResp.ProtoReflect.Descriptor instead.
func (*GetCourseListResp) Descriptor() ([]byte, []int) {
	return file_api_v1_base_info_course_course_proto_rawDescGZIP(), []int{2}
}

func (x *GetCourseListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCourseListResp) GetData() []*CourseList {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetCourseListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetCourseDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int32                  `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseDetailReq) Reset() {
	*x = GetCourseDetailReq{}
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseDetailReq) ProtoMessage() {}

func (x *GetCourseDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseDetailReq.ProtoReflect.Descriptor instead.
func (*GetCourseDetailReq) Descriptor() ([]byte, []int) {
	return file_api_v1_base_info_course_course_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourseDetailReq) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type GetCourseDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CourseList            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseDetailResp) Reset() {
	*x = GetCourseDetailResp{}
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseDetailResp) ProtoMessage() {}

func (x *GetCourseDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseDetailResp.ProtoReflect.Descriptor instead.
func (*GetCourseDetailResp) Descriptor() ([]byte, []int) {
	return file_api_v1_base_info_course_course_proto_rawDescGZIP(), []int{4}
}

func (x *GetCourseDetailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCourseDetailResp) GetData() *CourseList {
	if x != nil {
		return x.Data
	}
	return nil
}

type EditCourseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int32                  `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	CourseName    string                 `protobuf:"bytes,2,opt,name=courseName,proto3" json:"courseName,omitempty"`
	ClassName     string                 `protobuf:"bytes,3,opt,name=className,proto3" json:"className,omitempty"`
	TeacherIds    []int32                `protobuf:"varint,4,rep,packed,name=teacherIds,proto3" json:"teacherIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCourseReq) Reset() {
	*x = EditCourseReq{}
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCourseReq) ProtoMessage() {}

func (x *EditCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCourseReq.ProtoReflect.Descriptor instead.
func (*EditCourseReq) Descriptor() ([]byte, []int) {
	return file_api_v1_base_info_course_course_proto_rawDescGZIP(), []int{5}
}

func (x *EditCourseReq) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *EditCourseReq) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *EditCourseReq) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *EditCourseReq) GetTeacherIds() []int32 {
	if x != nil {
		return x.TeacherIds
	}
	return nil
}

type EditCourseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CourseList            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCourseResp) Reset() {
	*x = EditCourseResp{}
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCourseResp) ProtoMessage() {}

func (x *EditCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCourseResp.ProtoReflect.Descriptor instead.
func (*EditCourseResp) Descriptor() ([]byte, []int) {
	return file_api_v1_base_info_course_course_proto_rawDescGZIP(), []int{6}
}

func (x *EditCourseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EditCourseResp) GetData() *CourseList {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteCourseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseReq) Reset() {
	*x = DeleteCourseReq{}
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseReq) ProtoMessage() {}

func (x *DeleteCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseReq.ProtoReflect.Descriptor instead.
func (*DeleteCourseReq) Descriptor() ([]byte, []int) {
	return file_api_v1_base_info_course_course_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCourseReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCourseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResp) Reset() {
	*x = DeleteCourseResp{}
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResp) ProtoMessage() {}

func (x *DeleteCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResp.ProtoReflect.Descriptor instead.
func (*DeleteCourseResp) Descriptor() ([]byte, []int) {
	return file_api_v1_base_info_course_course_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCourseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetReq) Reset() {
	*x = ResetReq{}
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetReq) ProtoMessage() {}

func (x *ResetReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetReq.ProtoReflect.Descriptor instead.
func (*ResetReq) Descriptor() ([]byte, []int) {
	return file_api_v1_base_info_course_course_proto_rawDescGZIP(), []int{9}
}

type ResetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResp) Reset() {
	*x = ResetResp{}
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResp) ProtoMessage() {}

func (x *ResetResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_base_info_course_course_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResp.ProtoReflect.Descriptor instead.
func (*ResetResp) Descriptor() ([]byte, []int) {
	return file_api_v1_base_info_course_course_proto_rawDescGZIP(), []int{10}
}

func (x *ResetResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_v1_base_info_course_course_proto protoreflect.FileDescriptor

const file_api_v1_base_info_course_course_proto_rawDesc = "" +
	"\n" +
	"$api/v1/base_info/course/course.proto\x12\x17api.v1.base_info.course\x1a\x1cgoogle/api/annotations.proto\x1a&api/v1/base_info/teacher/teacher.proto\x1a&api/v1/base_info/student/student.proto\"\x88\x02\n" +
	"\n" +
	"CourseList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1e\n" +
	"\n" +
	"courseName\x18\x02 \x01(\tR\n" +
	"courseName\x12\x1c\n" +
	"\tclassName\x18\x03 \x01(\tR\tclassName\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12I\n" +
	"\vteacherList\x18\x04 \x03(\v2'.api.v1.base_info.teacher_i.TeacherInfoR\vteacherList\x12I\n" +
	"\vstudentList\x18\x05 \x03(\v2'.api.v1.base_info.student_i.StudentInfoR\vstudentList\"B\n" +
	"\x10GetCourseListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"|\n" +
	"\x11GetCourseListResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x02 \x03(\v2#.api.v1.base_info.course.CourseListR\x04data\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"0\n" +
	"\x12GetCourseDetailReq\x12\x1a\n" +
	"\bcourseId\x18\x01 \x01(\x05R\bcourseId\"h\n" +
	"\x13GetCourseDetailResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x02 \x01(\v2#.api.v1.base_info.course.CourseListR\x04data\"\x89\x01\n" +
	"\rEditCourseReq\x12\x1a\n" +
	"\bcourseId\x18\x01 \x01(\x05R\bcourseId\x12\x1e\n" +
	"\n" +
	"courseName\x18\x02 \x01(\tR\n" +
	"courseName\x12\x1c\n" +
	"\tclassName\x18\x03 \x01(\tR\tclassName\x12\x1e\n" +
	"\n" +
	"teacherIds\x18\x04 \x03(\x05R\n" +
	"teacherIds\"c\n" +
	"\x0eEditCourseResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x02 \x01(\v2#.api.v1.base_info.course.CourseListR\x04data\"!\n" +
	"\x0fDeleteCourseReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\",\n" +
	"\x10DeleteCourseResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\n" +
	"\n" +
	"\bResetReq\"%\n" +
	"\tResetResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa2\x05\n" +
	"\x06Course\x12\x84\x01\n" +
	"\x04List\x12).api.v1.base_info.course.GetCourseListReq\x1a*.api.v1.base_info.course.GetCourseListResp\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/base-info/course/list\x12\x8c\x01\n" +
	"\x06Detail\x12+.api.v1.base_info.course.GetCourseDetailReq\x1a,.api.v1.base_info.course.GetCourseDetailResp\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/base-info/course/detail\x12\x81\x01\n" +
	"\x04Edit\x12&.api.v1.base_info.course.EditCourseReq\x1a'.api.v1.base_info.course.EditCourseResp\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/base-info/course/edit\x12\x89\x01\n" +
	"\x06Delete\x12(.api.v1.base_info.course.DeleteCourseReq\x1a).api.v1.base_info.course.DeleteCourseResp\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/base-info/course/delete\x12r\n" +
	"\x05Reset\x12!.api.v1.base_info.course.ResetReq\x1a\".api.v1.base_info.course.ResetResp\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/base-info/resetBQ\n" +
	"\x17api.v1.base_info.courseP\x01Z4edu-evaluation-backed/api/v1/base_info/course;courseb\x06proto3"

var (
	file_api_v1_base_info_course_course_proto_rawDescOnce sync.Once
	file_api_v1_base_info_course_course_proto_rawDescData []byte
)

func file_api_v1_base_info_course_course_proto_rawDescGZIP() []byte {
	file_api_v1_base_info_course_course_proto_rawDescOnce.Do(func() {
		file_api_v1_base_info_course_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_base_info_course_course_proto_rawDesc), len(file_api_v1_base_info_course_course_proto_rawDesc)))
	})
	return file_api_v1_base_info_course_course_proto_rawDescData
}

var file_api_v1_base_info_course_course_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_v1_base_info_course_course_proto_goTypes = []any{
	(*CourseList)(nil),          // 0: api.v1.base_info.course.CourseList
	(*GetCourseListReq)(nil),    // 1: api.v1.base_info.course.GetCourseListReq
	(*GetCourseListResp)(nil),   // 2: api.v1.base_info.course.GetCourseListResp
	(*GetCourseDetailReq)(nil),  // 3: api.v1.base_info.course.GetCourseDetailReq
	(*GetCourseDetailResp)(nil), // 4: api.v1.base_info.course.GetCourseDetailResp
	(*EditCourseReq)(nil),       // 5: api.v1.base_info.course.EditCourseReq
	(*EditCourseResp)(nil),      // 6: api.v1.base_info.course.EditCourseResp
	(*DeleteCourseReq)(nil),     // 7: api.v1.base_info.course.DeleteCourseReq
	(*DeleteCourseResp)(nil),    // 8: api.v1.base_info.course.DeleteCourseResp
	(*ResetReq)(nil),            // 9: api.v1.base_info.course.ResetReq
	(*ResetResp)(nil),           // 10: api.v1.base_info.course.ResetResp
	(*teacher.TeacherInfo)(nil), // 11: api.v1.base_info.teacher_i.TeacherInfo
	(*student.StudentInfo)(nil), // 12: api.v1.base_info.student_i.StudentInfo
}
var file_api_v1_base_info_course_course_proto_depIdxs = []int32{
	11, // 0: api.v1.base_info.course.CourseList.teacherList:type_name -> api.v1.base_info.teacher_i.TeacherInfo
	12, // 1: api.v1.base_info.course.CourseList.studentList:type_name -> api.v1.base_info.student_i.StudentInfo
	0,  // 2: api.v1.base_info.course.GetCourseListResp.data:type_name -> api.v1.base_info.course.CourseList
	0,  // 3: api.v1.base_info.course.GetCourseDetailResp.data:type_name -> api.v1.base_info.course.CourseList
	0,  // 4: api.v1.base_info.course.EditCourseResp.data:type_name -> api.v1.base_info.course.CourseList
	1,  // 5: api.v1.base_info.course.Course.List:input_type -> api.v1.base_info.course.GetCourseListReq
	3,  // 6: api.v1.base_info.course.Course.Detail:input_type -> api.v1.base_info.course.GetCourseDetailReq
	5,  // 7: api.v1.base_info.course.Course.Edit:input_type -> api.v1.base_info.course.EditCourseReq
	7,  // 8: api.v1.base_info.course.Course.Delete:input_type -> api.v1.base_info.course.DeleteCourseReq
	9,  // 9: api.v1.base_info.course.Course.Reset:input_type -> api.v1.base_info.course.ResetReq
	2,  // 10: api.v1.base_info.course.Course.List:output_type -> api.v1.base_info.course.GetCourseListResp
	4,  // 11: api.v1.base_info.course.Course.Detail:output_type -> api.v1.base_info.course.GetCourseDetailResp
	6,  // 12: api.v1.base_info.course.Course.Edit:output_type -> api.v1.base_info.course.EditCourseResp
	8,  // 13: api.v1.base_info.course.Course.Delete:output_type -> api.v1.base_info.course.DeleteCourseResp
	10, // 14: api.v1.base_info.course.Course.Reset:output_type -> api.v1.base_info.course.ResetResp
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_base_info_course_course_proto_init() }
func file_api_v1_base_info_course_course_proto_init() {
	if File_api_v1_base_info_course_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_base_info_course_course_proto_rawDesc), len(file_api_v1_base_info_course_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_base_info_course_course_proto_goTypes,
		DependencyIndexes: file_api_v1_base_info_course_course_proto_depIdxs,
		MessageInfos:      file_api_v1_base_info_course_course_proto_msgTypes,
	}.Build()
	File_api_v1_base_info_course_course_proto = out.File
	file_api_v1_base_info_course_course_proto_goTypes = nil
	file_api_v1_base_info_course_course_proto_depIdxs = nil
}
