// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: api/v1/base_info/course/course.proto

package course

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCourseDetail = "/api.v1.base_info.course.Course/Detail"
const OperationCourseEdit = "/api.v1.base_info.course.Course/Edit"
const OperationCourseList = "/api.v1.base_info.course.Course/List"

type CourseHTTPServer interface {
	Detail(context.Context, *GetCourseDetailReq) (*GetCourseDetailResp, error)
	Edit(context.Context, *GetCourseListReq) (*GetCourseListResp, error)
	List(context.Context, *GetCourseListReq) (*GetCourseListResp, error)
}

func RegisterCourseHTTPServer(s *http.Server, srv CourseHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/base-info/course/list", _Course_List0_HTTP_Handler(srv))
	r.GET("/api/v1/base-info/course/detail", _Course_Detail0_HTTP_Handler(srv))
	r.POST("/api/v1/base-info/course/edit", _Course_Edit0_HTTP_Handler(srv))
}

func _Course_List0_HTTP_Handler(srv CourseHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCourseListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*GetCourseListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCourseListResp)
		return ctx.Result(200, reply)
	}
}

func _Course_Detail0_HTTP_Handler(srv CourseHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCourseDetailReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Detail(ctx, req.(*GetCourseDetailReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCourseDetailResp)
		return ctx.Result(200, reply)
	}
}

func _Course_Edit0_HTTP_Handler(srv CourseHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCourseListReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseEdit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Edit(ctx, req.(*GetCourseListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCourseListResp)
		return ctx.Result(200, reply)
	}
}

type CourseHTTPClient interface {
	Detail(ctx context.Context, req *GetCourseDetailReq, opts ...http.CallOption) (rsp *GetCourseDetailResp, err error)
	Edit(ctx context.Context, req *GetCourseListReq, opts ...http.CallOption) (rsp *GetCourseListResp, err error)
	List(ctx context.Context, req *GetCourseListReq, opts ...http.CallOption) (rsp *GetCourseListResp, err error)
}

type CourseHTTPClientImpl struct {
	cc *http.Client
}

func NewCourseHTTPClient(client *http.Client) CourseHTTPClient {
	return &CourseHTTPClientImpl{client}
}

func (c *CourseHTTPClientImpl) Detail(ctx context.Context, in *GetCourseDetailReq, opts ...http.CallOption) (*GetCourseDetailResp, error) {
	var out GetCourseDetailResp
	pattern := "/api/v1/base-info/course/detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCourseDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CourseHTTPClientImpl) Edit(ctx context.Context, in *GetCourseListReq, opts ...http.CallOption) (*GetCourseListResp, error) {
	var out GetCourseListResp
	pattern := "/api/v1/base-info/course/edit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCourseEdit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CourseHTTPClientImpl) List(ctx context.Context, in *GetCourseListReq, opts ...http.CallOption) (*GetCourseListResp, error) {
	var out GetCourseListResp
	pattern := "/api/v1/base-info/course/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCourseList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
