// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: api/v1/base_info/course/course.proto

package course

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Course_List_FullMethodName   = "/api.v1.base_info.course.Course/List"
	Course_Detail_FullMethodName = "/api.v1.base_info.course.Course/Detail"
	Course_Edit_FullMethodName   = "/api.v1.base_info.course.Course/Edit"
)

// CourseClient is the client API for Course service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CourseClient interface {
	List(ctx context.Context, in *GetCourseListReq, opts ...grpc.CallOption) (*GetCourseListResp, error)
	Detail(ctx context.Context, in *GetCourseDetailReq, opts ...grpc.CallOption) (*GetCourseDetailResp, error)
	Edit(ctx context.Context, in *GetCourseListReq, opts ...grpc.CallOption) (*GetCourseListResp, error)
}

type courseClient struct {
	cc grpc.ClientConnInterface
}

func NewCourseClient(cc grpc.ClientConnInterface) CourseClient {
	return &courseClient{cc}
}

func (c *courseClient) List(ctx context.Context, in *GetCourseListReq, opts ...grpc.CallOption) (*GetCourseListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourseListResp)
	err := c.cc.Invoke(ctx, Course_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseClient) Detail(ctx context.Context, in *GetCourseDetailReq, opts ...grpc.CallOption) (*GetCourseDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourseDetailResp)
	err := c.cc.Invoke(ctx, Course_Detail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseClient) Edit(ctx context.Context, in *GetCourseListReq, opts ...grpc.CallOption) (*GetCourseListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourseListResp)
	err := c.cc.Invoke(ctx, Course_Edit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourseServer is the server API for Course service.
// All implementations must embed UnimplementedCourseServer
// for forward compatibility.
type CourseServer interface {
	List(context.Context, *GetCourseListReq) (*GetCourseListResp, error)
	Detail(context.Context, *GetCourseDetailReq) (*GetCourseDetailResp, error)
	Edit(context.Context, *GetCourseListReq) (*GetCourseListResp, error)
	mustEmbedUnimplementedCourseServer()
}

// UnimplementedCourseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCourseServer struct{}

func (UnimplementedCourseServer) List(context.Context, *GetCourseListReq) (*GetCourseListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCourseServer) Detail(context.Context, *GetCourseDetailReq) (*GetCourseDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Detail not implemented")
}
func (UnimplementedCourseServer) Edit(context.Context, *GetCourseListReq) (*GetCourseListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Edit not implemented")
}
func (UnimplementedCourseServer) mustEmbedUnimplementedCourseServer() {}
func (UnimplementedCourseServer) testEmbeddedByValue()                {}

// UnsafeCourseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourseServer will
// result in compilation errors.
type UnsafeCourseServer interface {
	mustEmbedUnimplementedCourseServer()
}

func RegisterCourseServer(s grpc.ServiceRegistrar, srv CourseServer) {
	// If the following call panics, it indicates UnimplementedCourseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Course_ServiceDesc, srv)
}

func _Course_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Course_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServer).List(ctx, req.(*GetCourseListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Course_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Course_Detail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServer).Detail(ctx, req.(*GetCourseDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Course_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Course_Edit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServer).Edit(ctx, req.(*GetCourseListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Course_ServiceDesc is the grpc.ServiceDesc for Course service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Course_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.base_info.course.Course",
	HandlerType: (*CourseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Course_List_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _Course_Detail_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _Course_Edit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/base_info/course/course.proto",
}
