// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: v1/auth/auth.proto

package auth

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAuthAdminLogin = "/api.v1.auth.Auth/AdminLogin"
const OperationAuthStudentInfo = "/api.v1.auth.Auth/StudentInfo"
const OperationAuthStudentLogin = "/api.v1.auth.Auth/StudentLogin"

type AuthHTTPServer interface {
	AdminLogin(context.Context, *AdminLoginReq) (*AdminLoginResp, error)
	StudentInfo(context.Context, *StudentInfoReq) (*StudentInfoResp, error)
	StudentLogin(context.Context, *StudentLoginReq) (*StudentLoginResp, error)
}

func RegisterAuthHTTPServer(s *http.Server, srv AuthHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/auth/admin/login", _Auth_AdminLogin0_HTTP_Handler(srv))
	r.POST("/api/v1/auth/student/login", _Auth_StudentLogin0_HTTP_Handler(srv))
	r.GET("/api/v1/auth/student/info", _Auth_StudentInfo0_HTTP_Handler(srv))
}

func _Auth_AdminLogin0_HTTP_Handler(srv AuthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminLoginReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthAdminLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminLogin(ctx, req.(*AdminLoginReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminLoginResp)
		return ctx.Result(200, reply)
	}
}

func _Auth_StudentLogin0_HTTP_Handler(srv AuthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StudentLoginReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthStudentLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StudentLogin(ctx, req.(*StudentLoginReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StudentLoginResp)
		return ctx.Result(200, reply)
	}
}

func _Auth_StudentInfo0_HTTP_Handler(srv AuthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StudentInfoReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthStudentInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StudentInfo(ctx, req.(*StudentInfoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StudentInfoResp)
		return ctx.Result(200, reply)
	}
}

type AuthHTTPClient interface {
	AdminLogin(ctx context.Context, req *AdminLoginReq, opts ...http.CallOption) (rsp *AdminLoginResp, err error)
	StudentInfo(ctx context.Context, req *StudentInfoReq, opts ...http.CallOption) (rsp *StudentInfoResp, err error)
	StudentLogin(ctx context.Context, req *StudentLoginReq, opts ...http.CallOption) (rsp *StudentLoginResp, err error)
}

type AuthHTTPClientImpl struct {
	cc *http.Client
}

func NewAuthHTTPClient(client *http.Client) AuthHTTPClient {
	return &AuthHTTPClientImpl{client}
}

func (c *AuthHTTPClientImpl) AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...http.CallOption) (*AdminLoginResp, error) {
	var out AdminLoginResp
	pattern := "/api/v1/auth/admin/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthAdminLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AuthHTTPClientImpl) StudentInfo(ctx context.Context, in *StudentInfoReq, opts ...http.CallOption) (*StudentInfoResp, error) {
	var out StudentInfoResp
	pattern := "/api/v1/auth/student/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuthStudentInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AuthHTTPClientImpl) StudentLogin(ctx context.Context, in *StudentLoginReq, opts ...http.CallOption) (*StudentLoginResp, error) {
	var out StudentLoginResp
	pattern := "/api/v1/auth/student/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthStudentLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
