// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: v1/auth/auth.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginReq) Reset() {
	*x = AdminLoginReq{}
	mi := &file_v1_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginReq) ProtoMessage() {}

func (x *AdminLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginReq.ProtoReflect.Descriptor instead.
func (*AdminLoginReq) Descriptor() ([]byte, []int) {
	return file_v1_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AdminLoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginResp) Reset() {
	*x = AdminLoginResp{}
	mi := &file_v1_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginResp) ProtoMessage() {}

func (x *AdminLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginResp.ProtoReflect.Descriptor instead.
func (*AdminLoginResp) Descriptor() ([]byte, []int) {
	return file_v1_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AdminLoginResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StudentLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StuNo         string                 `protobuf:"bytes,1,opt,name=stuNo,proto3" json:"stuNo,omitempty"`
	CardNo        string                 `protobuf:"bytes,2,opt,name=cardNo,proto3" json:"cardNo,omitempty"`
	TaskId        uint32                 `protobuf:"varint,3,opt,name=taskId,proto3" json:"taskId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentLoginReq) Reset() {
	*x = StudentLoginReq{}
	mi := &file_v1_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentLoginReq) ProtoMessage() {}

func (x *StudentLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentLoginReq.ProtoReflect.Descriptor instead.
func (*StudentLoginReq) Descriptor() ([]byte, []int) {
	return file_v1_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *StudentLoginReq) GetStuNo() string {
	if x != nil {
		return x.StuNo
	}
	return ""
}

func (x *StudentLoginReq) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *StudentLoginReq) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type StudentLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          *StudentData           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentLoginResp) Reset() {
	*x = StudentLoginResp{}
	mi := &file_v1_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentLoginResp) ProtoMessage() {}

func (x *StudentLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentLoginResp.ProtoReflect.Descriptor instead.
func (*StudentLoginResp) Descriptor() ([]byte, []int) {
	return file_v1_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *StudentLoginResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StudentLoginResp) GetData() *StudentData {
	if x != nil {
		return x.Data
	}
	return nil
}

type StudentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentNo     string                 `protobuf:"bytes,1,opt,name=studentNo,proto3" json:"studentNo,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentData) Reset() {
	*x = StudentData{}
	mi := &file_v1_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentData) ProtoMessage() {}

func (x *StudentData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentData.ProtoReflect.Descriptor instead.
func (*StudentData) Descriptor() ([]byte, []int) {
	return file_v1_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *StudentData) GetStudentNo() string {
	if x != nil {
		return x.StudentNo
	}
	return ""
}

func (x *StudentData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StudentInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StuNo         string                 `protobuf:"bytes,1,opt,name=stuNo,proto3" json:"stuNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentInfoReq) Reset() {
	*x = StudentInfoReq{}
	mi := &file_v1_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentInfoReq) ProtoMessage() {}

func (x *StudentInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentInfoReq.ProtoReflect.Descriptor instead.
func (*StudentInfoReq) Descriptor() ([]byte, []int) {
	return file_v1_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *StudentInfoReq) GetStuNo() string {
	if x != nil {
		return x.StuNo
	}
	return ""
}

type StudentInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          *StudentDetailInfo     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentInfoResp) Reset() {
	*x = StudentInfoResp{}
	mi := &file_v1_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentInfoResp) ProtoMessage() {}

func (x *StudentInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentInfoResp.ProtoReflect.Descriptor instead.
func (*StudentInfoResp) Descriptor() ([]byte, []int) {
	return file_v1_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *StudentInfoResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StudentInfoResp) GetData() *StudentDetailInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type StudentDetailInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sex           string                 `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	StudentNo     string                 `protobuf:"bytes,4,opt,name=studentNo,proto3" json:"studentNo,omitempty"`
	IdCardNo      string                 `protobuf:"bytes,5,opt,name=idCardNo,proto3" json:"idCardNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentDetailInfo) Reset() {
	*x = StudentDetailInfo{}
	mi := &file_v1_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentDetailInfo) ProtoMessage() {}

func (x *StudentDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentDetailInfo.ProtoReflect.Descriptor instead.
func (*StudentDetailInfo) Descriptor() ([]byte, []int) {
	return file_v1_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *StudentDetailInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentDetailInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentDetailInfo) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *StudentDetailInfo) GetStudentNo() string {
	if x != nil {
		return x.StudentNo
	}
	return ""
}

func (x *StudentDetailInfo) GetIdCardNo() string {
	if x != nil {
		return x.IdCardNo
	}
	return ""
}

var File_v1_auth_auth_proto protoreflect.FileDescriptor

const file_v1_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x12v1/auth/auth.proto\x12\vapi.v1.auth\x1a\x1cgoogle/api/annotations.proto\"G\n" +
	"\rAdminLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"*\n" +
	"\x0eAdminLoginResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"W\n" +
	"\x0fStudentLoginReq\x12\x14\n" +
	"\x05stuNo\x18\x01 \x01(\tR\x05stuNo\x12\x16\n" +
	"\x06cardNo\x18\x02 \x01(\tR\x06cardNo\x12\x16\n" +
	"\x06taskId\x18\x03 \x01(\rR\x06taskId\"Z\n" +
	"\x10StudentLoginResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12,\n" +
	"\x04data\x18\x02 \x01(\v2\x18.api.v1.auth.StudentDataR\x04data\"?\n" +
	"\vStudentData\x12\x1c\n" +
	"\tstudentNo\x18\x01 \x01(\tR\tstudentNo\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"&\n" +
	"\x0eStudentInfoReq\x12\x14\n" +
	"\x05stuNo\x18\x01 \x01(\tR\x05stuNo\"_\n" +
	"\x0fStudentInfoResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x122\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.api.v1.auth.StudentDetailInfoR\x04data\"\x83\x01\n" +
	"\x11StudentDetailInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\tR\x03sex\x12\x1c\n" +
	"\tstudentNo\x18\x04 \x01(\tR\tstudentNo\x12\x1a\n" +
	"\bidCardNo\x18\x05 \x01(\tR\bidCardNo2\xd3\x02\n" +
	"\x04Auth\x12j\n" +
	"\n" +
	"AdminLogin\x12\x1a.api.v1.auth.AdminLoginReq\x1a\x1b.api.v1.auth.AdminLoginResp\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/auth/admin/login\x12r\n" +
	"\fStudentLogin\x12\x1c.api.v1.auth.StudentLoginReq\x1a\x1d.api.v1.auth.StudentLoginResp\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/auth/student/login\x12k\n" +
	"\vStudentInfo\x12\x1b.api.v1.auth.StudentInfoReq\x1a\x1c.api.v1.auth.StudentInfoResp\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/auth/student/infoB7\n" +
	"\vapi.v1.authP\x01Z&edu-evaluation-backed/api/v1/auth;authb\x06proto3"

var (
	file_v1_auth_auth_proto_rawDescOnce sync.Once
	file_v1_auth_auth_proto_rawDescData []byte
)

func file_v1_auth_auth_proto_rawDescGZIP() []byte {
	file_v1_auth_auth_proto_rawDescOnce.Do(func() {
		file_v1_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_auth_auth_proto_rawDesc), len(file_v1_auth_auth_proto_rawDesc)))
	})
	return file_v1_auth_auth_proto_rawDescData
}

var file_v1_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_auth_auth_proto_goTypes = []any{
	(*AdminLoginReq)(nil),     // 0: api.v1.auth.AdminLoginReq
	(*AdminLoginResp)(nil),    // 1: api.v1.auth.AdminLoginResp
	(*StudentLoginReq)(nil),   // 2: api.v1.auth.StudentLoginReq
	(*StudentLoginResp)(nil),  // 3: api.v1.auth.StudentLoginResp
	(*StudentData)(nil),       // 4: api.v1.auth.StudentData
	(*StudentInfoReq)(nil),    // 5: api.v1.auth.StudentInfoReq
	(*StudentInfoResp)(nil),   // 6: api.v1.auth.StudentInfoResp
	(*StudentDetailInfo)(nil), // 7: api.v1.auth.StudentDetailInfo
}
var file_v1_auth_auth_proto_depIdxs = []int32{
	4, // 0: api.v1.auth.StudentLoginResp.data:type_name -> api.v1.auth.StudentData
	7, // 1: api.v1.auth.StudentInfoResp.data:type_name -> api.v1.auth.StudentDetailInfo
	0, // 2: api.v1.auth.Auth.AdminLogin:input_type -> api.v1.auth.AdminLoginReq
	2, // 3: api.v1.auth.Auth.StudentLogin:input_type -> api.v1.auth.StudentLoginReq
	5, // 4: api.v1.auth.Auth.StudentInfo:input_type -> api.v1.auth.StudentInfoReq
	1, // 5: api.v1.auth.Auth.AdminLogin:output_type -> api.v1.auth.AdminLoginResp
	3, // 6: api.v1.auth.Auth.StudentLogin:output_type -> api.v1.auth.StudentLoginResp
	6, // 7: api.v1.auth.Auth.StudentInfo:output_type -> api.v1.auth.StudentInfoResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_auth_auth_proto_init() }
func file_v1_auth_auth_proto_init() {
	if File_v1_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_auth_auth_proto_rawDesc), len(file_v1_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_auth_auth_proto_goTypes,
		DependencyIndexes: file_v1_auth_auth_proto_depIdxs,
		MessageInfos:      file_v1_auth_auth_proto_msgTypes,
	}.Build()
	File_v1_auth_auth_proto = out.File
	file_v1_auth_auth_proto_goTypes = nil
	file_v1_auth_auth_proto_depIdxs = nil
}
