// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: api/v1/auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Auth_AdminLogin_FullMethodName          = "/api.v1.auth.Auth/AdminLogin"
	Auth_StudentLogin_FullMethodName        = "/api.v1.auth.Auth/StudentLogin"
	Auth_StudentInfo_FullMethodName         = "/api.v1.auth.Auth/StudentInfo"
	Auth_AdminChangePassword_FullMethodName = "/api.v1.auth.Auth/AdminChangePassword"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginResp, error)
	StudentLogin(ctx context.Context, in *StudentLoginReq, opts ...grpc.CallOption) (*StudentLoginResp, error)
	StudentInfo(ctx context.Context, in *StudentInfoReq, opts ...grpc.CallOption) (*StudentInfoResp, error)
	AdminChangePassword(ctx context.Context, in *AdminChangePasswordReq, opts ...grpc.CallOption) (*AdminChangePasswordResp, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminLoginResp)
	err := c.cc.Invoke(ctx, Auth_AdminLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) StudentLogin(ctx context.Context, in *StudentLoginReq, opts ...grpc.CallOption) (*StudentLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentLoginResp)
	err := c.cc.Invoke(ctx, Auth_StudentLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) StudentInfo(ctx context.Context, in *StudentInfoReq, opts ...grpc.CallOption) (*StudentInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentInfoResp)
	err := c.cc.Invoke(ctx, Auth_StudentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) AdminChangePassword(ctx context.Context, in *AdminChangePasswordReq, opts ...grpc.CallOption) (*AdminChangePasswordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminChangePasswordResp)
	err := c.cc.Invoke(ctx, Auth_AdminChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility.
type AuthServer interface {
	AdminLogin(context.Context, *AdminLoginReq) (*AdminLoginResp, error)
	StudentLogin(context.Context, *StudentLoginReq) (*StudentLoginResp, error)
	StudentInfo(context.Context, *StudentInfoReq) (*StudentInfoResp, error)
	AdminChangePassword(context.Context, *AdminChangePasswordReq) (*AdminChangePasswordResp, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServer struct{}

func (UnimplementedAuthServer) AdminLogin(context.Context, *AdminLoginReq) (*AdminLoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminLogin not implemented")
}
func (UnimplementedAuthServer) StudentLogin(context.Context, *StudentLoginReq) (*StudentLoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StudentLogin not implemented")
}
func (UnimplementedAuthServer) StudentInfo(context.Context, *StudentInfoReq) (*StudentInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StudentInfo not implemented")
}
func (UnimplementedAuthServer) AdminChangePassword(context.Context, *AdminChangePasswordReq) (*AdminChangePasswordResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminChangePassword not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}
func (UnimplementedAuthServer) testEmbeddedByValue()              {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	// If the following call panics, it indicates UnimplementedAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_AdminLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AdminLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AdminLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AdminLogin(ctx, req.(*AdminLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_StudentLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).StudentLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_StudentLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).StudentLogin(ctx, req.(*StudentLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_StudentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).StudentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_StudentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).StudentInfo(ctx, req.(*StudentInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_AdminChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminChangePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AdminChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AdminChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AdminChangePassword(ctx, req.(*AdminChangePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminLogin",
			Handler:    _Auth_AdminLogin_Handler,
		},
		{
			MethodName: "StudentLogin",
			Handler:    _Auth_StudentLogin_Handler,
		},
		{
			MethodName: "StudentInfo",
			Handler:    _Auth_StudentInfo_Handler,
		},
		{
			MethodName: "AdminChangePassword",
			Handler:    _Auth_AdminChangePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/auth/auth.proto",
}
