// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: api/v1/eva_question/question.proto

package eva_question

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationQuestionListQuestions = "/api.v1.eva_question.Question/ListQuestions"
const OperationQuestionUpdateQuestions = "/api.v1.eva_question.Question/UpdateQuestions"

type QuestionHTTPServer interface {
	ListQuestions(context.Context, *ListQuestionsReq) (*ListQuestionsResp, error)
	UpdateQuestions(context.Context, *UpdateQuestionsReq) (*UpdateQuestionsResp, error)
}

func RegisterQuestionHTTPServer(s *http.Server, srv QuestionHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/question/list", _Question_ListQuestions0_HTTP_Handler(srv))
	r.POST("/api/v1/question/update", _Question_UpdateQuestions0_HTTP_Handler(srv))
}

func _Question_ListQuestions0_HTTP_Handler(srv QuestionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListQuestionsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQuestionListQuestions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListQuestions(ctx, req.(*ListQuestionsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListQuestionsResp)
		return ctx.Result(200, reply)
	}
}

func _Question_UpdateQuestions0_HTTP_Handler(srv QuestionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateQuestionsReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQuestionUpdateQuestions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateQuestions(ctx, req.(*UpdateQuestionsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateQuestionsResp)
		return ctx.Result(200, reply)
	}
}

type QuestionHTTPClient interface {
	ListQuestions(ctx context.Context, req *ListQuestionsReq, opts ...http.CallOption) (rsp *ListQuestionsResp, err error)
	UpdateQuestions(ctx context.Context, req *UpdateQuestionsReq, opts ...http.CallOption) (rsp *UpdateQuestionsResp, err error)
}

type QuestionHTTPClientImpl struct {
	cc *http.Client
}

func NewQuestionHTTPClient(client *http.Client) QuestionHTTPClient {
	return &QuestionHTTPClientImpl{client}
}

func (c *QuestionHTTPClientImpl) ListQuestions(ctx context.Context, in *ListQuestionsReq, opts ...http.CallOption) (*ListQuestionsResp, error) {
	var out ListQuestionsResp
	pattern := "/api/v1/question/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationQuestionListQuestions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *QuestionHTTPClientImpl) UpdateQuestions(ctx context.Context, in *UpdateQuestionsReq, opts ...http.CallOption) (*UpdateQuestionsResp, error) {
	var out UpdateQuestionsResp
	pattern := "/api/v1/question/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationQuestionUpdateQuestions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
