// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/v1/eva_question/question.proto

package eva_question

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionItem) Reset() {
	*x = QuestionItem{}
	mi := &file_api_v1_eva_question_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionItem) ProtoMessage() {}

func (x *QuestionItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_question_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionItem.ProtoReflect.Descriptor instead.
func (*QuestionItem) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_question_question_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *QuestionItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuestionItem) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type ListQuestionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionsReq) Reset() {
	*x = ListQuestionsReq{}
	mi := &file_api_v1_eva_question_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsReq) ProtoMessage() {}

func (x *ListQuestionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_question_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsReq.ProtoReflect.Descriptor instead.
func (*ListQuestionsReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_question_question_proto_rawDescGZIP(), []int{1}
}

type ListQuestionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*QuestionItem        `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionsResp) Reset() {
	*x = ListQuestionsResp{}
	mi := &file_api_v1_eva_question_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsResp) ProtoMessage() {}

func (x *ListQuestionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_question_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsResp.ProtoReflect.Descriptor instead.
func (*ListQuestionsResp) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_question_question_proto_rawDescGZIP(), []int{2}
}

func (x *ListQuestionsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListQuestionsResp) GetData() []*QuestionItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateQuestionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*QuestionItem        `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionsReq) Reset() {
	*x = UpdateQuestionsReq{}
	mi := &file_api_v1_eva_question_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionsReq) ProtoMessage() {}

func (x *UpdateQuestionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_question_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionsReq.ProtoReflect.Descriptor instead.
func (*UpdateQuestionsReq) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_question_question_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateQuestionsReq) GetQuestions() []*QuestionItem {
	if x != nil {
		return x.Questions
	}
	return nil
}

type UpdateQuestionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionsResp) Reset() {
	*x = UpdateQuestionsResp{}
	mi := &file_api_v1_eva_question_question_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionsResp) ProtoMessage() {}

func (x *UpdateQuestionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_eva_question_question_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionsResp.ProtoReflect.Descriptor instead.
func (*UpdateQuestionsResp) Descriptor() ([]byte, []int) {
	return file_api_v1_eva_question_question_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateQuestionsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_v1_eva_question_question_proto protoreflect.FileDescriptor

const file_api_v1_eva_question_question_proto_rawDesc = "" +
	"\n" +
	"\"api/v1/eva_question/question.proto\x12\x13api.v1.eva_question\x1a\x1cgoogle/api/annotations.proto\"b\n" +
	"\fQuestionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\"\x12\n" +
	"\x10ListQuestionsReq\"d\n" +
	"\x11ListQuestionsResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x02 \x03(\v2!.api.v1.eva_question.QuestionItemR\x04data\"U\n" +
	"\x12UpdateQuestionsReq\x12?\n" +
	"\tquestions\x18\x01 \x03(\v2!.api.v1.eva_question.QuestionItemR\tquestions\"/\n" +
	"\x13UpdateQuestionsResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x94\x02\n" +
	"\bQuestion\x12}\n" +
	"\rListQuestions\x12%.api.v1.eva_question.ListQuestionsReq\x1a&.api.v1.eva_question.ListQuestionsResp\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/question/list\x12\x88\x01\n" +
	"\x0fUpdateQuestions\x12'.api.v1.eva_question.UpdateQuestionsReq\x1a(.api.v1.eva_question.UpdateQuestionsResp\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/question/updateB8Z6edu-evaluation-backed/api/v1/eva_question;eva_questionb\x06proto3"

var (
	file_api_v1_eva_question_question_proto_rawDescOnce sync.Once
	file_api_v1_eva_question_question_proto_rawDescData []byte
)

func file_api_v1_eva_question_question_proto_rawDescGZIP() []byte {
	file_api_v1_eva_question_question_proto_rawDescOnce.Do(func() {
		file_api_v1_eva_question_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_eva_question_question_proto_rawDesc), len(file_api_v1_eva_question_question_proto_rawDesc)))
	})
	return file_api_v1_eva_question_question_proto_rawDescData
}

var file_api_v1_eva_question_question_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_eva_question_question_proto_goTypes = []any{
	(*QuestionItem)(nil),        // 0: api.v1.eva_question.QuestionItem
	(*ListQuestionsReq)(nil),    // 1: api.v1.eva_question.ListQuestionsReq
	(*ListQuestionsResp)(nil),   // 2: api.v1.eva_question.ListQuestionsResp
	(*UpdateQuestionsReq)(nil),  // 3: api.v1.eva_question.UpdateQuestionsReq
	(*UpdateQuestionsResp)(nil), // 4: api.v1.eva_question.UpdateQuestionsResp
}
var file_api_v1_eva_question_question_proto_depIdxs = []int32{
	0, // 0: api.v1.eva_question.ListQuestionsResp.data:type_name -> api.v1.eva_question.QuestionItem
	0, // 1: api.v1.eva_question.UpdateQuestionsReq.questions:type_name -> api.v1.eva_question.QuestionItem
	1, // 2: api.v1.eva_question.Question.ListQuestions:input_type -> api.v1.eva_question.ListQuestionsReq
	3, // 3: api.v1.eva_question.Question.UpdateQuestions:input_type -> api.v1.eva_question.UpdateQuestionsReq
	2, // 4: api.v1.eva_question.Question.ListQuestions:output_type -> api.v1.eva_question.ListQuestionsResp
	4, // 5: api.v1.eva_question.Question.UpdateQuestions:output_type -> api.v1.eva_question.UpdateQuestionsResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_eva_question_question_proto_init() }
func file_api_v1_eva_question_question_proto_init() {
	if File_api_v1_eva_question_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_eva_question_question_proto_rawDesc), len(file_api_v1_eva_question_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_eva_question_question_proto_goTypes,
		DependencyIndexes: file_api_v1_eva_question_question_proto_depIdxs,
		MessageInfos:      file_api_v1_eva_question_question_proto_msgTypes,
	}.Build()
	File_api_v1_eva_question_question_proto = out.File
	file_api_v1_eva_question_question_proto_goTypes = nil
	file_api_v1_eva_question_question_proto_depIdxs = nil
}
